services:
  web:
    container_name: domakin-web
    build:
      context: domakin
    ports:
      - "8000:8000"
    volumes:
      - ./domakin:/app
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"

  celery-worker:
    build:
      context: domakin
    command: "celery -A domakin worker --loglevel=info"
    volumes:
      - ./domakin:/app
    depends_on:
      - redis

  celery-beat:
    build:
      context: domakin
    command: "celery -A domakin beat --loglevel=info"
    volumes:
      - ./domakin:/app
    depends_on:
      - redis

  tailwind:
    build:
      context: domakin
    command: "python manage.py tailwind start"
    volumes:
      - ./domakin:/app
    tty: true
    depends_on:
      - web
