# Generated by Django 5.1.4 on 2025-01-03 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_completed_task_is_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_completed', '-created']},
        ),
    ]
