# Generated by Django 5.1.4 on 2024-12-27 19:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_family_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
