# Generated by Django 5.1.4 on 2024-12-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0003_alter_family_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='created_by',
        ),
        migrations.AddField(
            model_name='familymember',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
