# Generated by Django 5.1.4 on 2024-12-28 18:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0004_remove_family_created_by_familymember_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='families.family')),
            ],
        ),
    ]
